# -*- coding: utf-8 -*-
"""fgsm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwC4LDRSo8HlxN2Tw2iKhHa2-_iuHo9_
"""

import tensorflow as tf

class FGSM_Attack:
    def __init__(self, model):
        self.model = model

    def generate(self, image, label, epsilon):
        image = tf.cast(image, tf.float32)

        with tf.GradientTape() as tape:
            tape.watch(image)
            prediction = self.model(image)
            loss = tf.keras.losses.sparse_categorical_crossentropy(label, prediction, from_logits=True)

        gradient = tape.gradient(loss, image)
        signed_grad = tf.sign(gradient)

        adversarial = image + epsilon * signed_grad
        adversarial = tf.clip_by_value(adversarial, 0, 1)

        return adversarial

